name: '🔑 Gitleaks — Secret Scanning'

on:
  push:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: 'bash'

jobs:
  gitleaks:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8' # ratchet:actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 'Run Gitleaks'
        uses: 'gitleaks/gitleaks-action@v2'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'